name: Create Branch & Build and deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Configure Git âš™ï¸
        run: |
          git config --global user.email "pawel.rogowski.praca@gmail.com"
          git config --global user.name "pawelrogowski"

      - name: Create gh-pages branch if it doesn't exist ğŸŒ³
        run: |
          if [ -z "$(git ls-remote --heads origin gh-pages)" ]; then
            git checkout -b gh-pages
            git push -u origin gh-pages
            git checkout -
          else
            git checkout gh-pages
            git pull origin gh-pages
            git checkout -
          fi

      - name: Copy main branch to gh-pages branch ğŸ”„
        run: |
          git checkout main
          git pull origin main
          git checkout gh-pages
          git pull origin gh-pages
          cp -r $GITHUB_WORKSPACE/* .
          git add .
          git commit -m "Update gh-pages branch"
          git push origin gh-pages
          git checkout -

      - name: Install, lint, build ğŸ”§
        run: |
          npm install
          npm run lint:js
          npm run build

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: build
